language: node_js
node_js:
 - "stable"
services:
  - docker

before_install:
    sudo apt-get install docker-compose

install:
    # Docker CFML Server Tests
  - docker-compose build
  - docker-compose up -d

script:
  - ls
  - docker-compose up -d
  - docker-compose stop

branches:
  only:
    - master
    - main
    - travis_ci_cd
