language: node_js
node_js:
 - "stable"
sudo: required
services:
  - docker

env:
    DOCKER_COMPOSE_VERSION: 3.1

before_install:
    # update is required to update the repositories to see the new packages for
    # Docker.
    - sudo apt-get update
    # Now we can install the newer docker-engine which is required for the newer
    # docker-composer we will install next. The messy options are to force it to
    # be non-interactive (normally it asks you a bunch of config questions).
    - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
    - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
    - sudo apt-get update
    - sudo apt-get -y install docker-ce
    # Print out the current docker-compose version. Once this reports 1.6+ then we
    # do not need the following steps.
    - docker-compose --version
    # As of the writing of this script Travis has docker-compose v1.4.2, we need
    # to update it to 1.8+. $DOCKER_COMPOSE_VERSION is provide from the `env`
    # above.
    # Setup your application stack. You may need to tweak these commands if you
    # doing out-of-the-ordinary docker-compose builds.
    
    - docker-compose build
    - docker-compose up -d
    - docker-compose stop

script:
  - ls

branches:
  only:
    - master
    - main
    - travis_ci_cd
