language: node_js
node_js:
 - "stable"
services:
  - docker

before_script:
    sudo apt-get install docker-compose

script:
  - ls
  - docker-compose up -d
  - docker-compose stop

branches:
  only:
    - master
    - main
    - travis_ci_cd
