version: "3.1"

services:
  backend:
    container_name: chatroom-backend
    build: ./backend-T0
    ports:
     - 3001:3001
    environment:
      - DATABASE_PORT=5432
      - DATABASE_HOST=grupo21db.c3mk7kgq7w7h.us-east-2.rds.amazonaws.com
      - DATABASE_DBNAME=postgres
      - DATABASE_USER=grupo21
      - endpoint_aws_comprehend=https://qaoxmqp1g8.execute-api.us-east-2.amazonaws.com/default/nueva-sentiment
      - s3_bucket=chat-grupo-21
    volumes:
     - .:/code
     - ./data/certbot/conf:/etc/letsencrypt
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        npm run start --prefix backend-T0

  frontend:
    tty: true
    environment:
      BACKEND_HOST: backend
    build:
        context: ./frontend-t0
        dockerfile: Dockerfile
    container_name: chatroom-frontend
    restart: always
    links:
      - "backend:localhost"
    ports:
      - 3000:3000
    volumes:
      - ./front:/front
      - /front/node_modules
  nginx:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    restart: unless-stopped
    container_name: nginx
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
  
    tty: true
    environment:
      BACKEND_HOST: backend
    build:
        context: ./frontend-t0
        dockerfile: Dockerfile
    container_name: chatroom-frontend
    restart: always
    links:
      - "backend:localhost"
    ports:
      - 3000:3000
      - 3002:3002
    volumes:
      - ./front:/front
      - /front/node_modules
  authentication:
    container_name: auth-container
    build: ./authentication
    ports:
      - 3002:3002
    environment:
      - DATABASE_PORT=5432
      - DATABASE_HOST=database
      - DATABASE_DBNAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=root

    volumes:
      - .:/code
    links:
      - "postgres:database"
    depends_on:
      - postgres
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        npm run start --prefix authentication

volumes:
  my_dbdata:
  certificate_data:

