version: "3.1"

services:
  backend:
    container_name: chatroom-backend
    build: ./backend-T0
    ports:
     - 3001:3001
    env_file:
      - .env
    volumes:
     - .:/code
     - ./data/certbot/conf:/etc/letsencrypt
    links:
      - "postgres:database"
    depends_on:
      - postgres
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        npm run start --prefix backend-T0
        
  postgres:
    build: ./postgres
    container_name: chatroom-database
    ports:
      - 5432:5432
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    expose:
      - 5432
  frontend:
    tty: true
    environment:
      BACKEND_HOST: backend
    build:
        context: ./frontend-t0
        dockerfile: Dockerfile
    container_name: chatroom-frontend
    restart: always
    links:
      - "backend:localhost"
    ports:
      - 3000:3000
    volumes:
      - ./front:/front
      - /front/node_modules
  nginx:
    image: nginx:1.13 # this will use the latest version of 1.13.x
    restart: unless-stopped
    container_name: nginx
    ports:
      - '80:80' # expose 80 on host and sent to 80 in container
      - "443:443"
    depends_on: 
      - frontend
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  my_dbdata:
  certificate_data: