version: "3.1"

services:
  backend:
    container_name: chatroom-backend
    build: ./backend-T0
    ports:
     - 3001:3001
    environment:
      - DATABASE_PORT=5432
      - DATABASE_HOST=database
      - DATABASE_DBNAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=root
      - endpoint_aws_comprehend=https://qaoxmqp1g8.execute-api.us-east-2.amazonaws.com/default/nueva-sentiment
      - s3_bucket=chat-grupo-21
      - JWT_SECRET=Grupo21-arquiSoft
    volumes:
     - .:/code
    links:
      - "postgres:database"
    depends_on:
      - postgres
    restart: always
    command:
      - /bin/sh
      - -c
      - |
        npm run start --prefix backend-T0

  postgres:
    build: ./postgres
    container_name: chatroom-database
    ports:
      - 5432:5432
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
    expose:
      - 5432
  frontend:
    tty: true
    environment:
      BACKEND_HOST: backend
    build:
        context: ./frontend-t0
        dockerfile: Dockerfile
    container_name: chatroom-frontend
    restart: always
    links:
      - "backend:localhost"
    ports:
      - 3000:3000
    volumes:
      - ./front:/front
      - /front/node_modules
volumes:
  my_dbdata:
  certificate_data:
